In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('CountriesSD.csv')

In [ ]:
df.head(5)

   Unnamed: 0          Country Code  Population  GDP per Capita
0           0      Afghanistan  AFG  32526562.0      594.323081
1           1          Albania  ALB   2889167.0     3945.217582
2           2          Algeria  ALG  39666519.0     4206.031232
3           3  American Samoa*  ASA     55538.0             NaN
4           4          Andorra  AND     70473.0             NaN

In [ ]:
df.shape

(201, 5)

In [ ]:
df.isnull().sum()

Unnamed: 0         0
Country            0
Code               0
Population         5
GDP per Capita    25
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(30)

In [ ]:
df=df.fillna(value=0)

In [ ]:
df

     Unnamed: 0          Country Code  Population  GDP per Capita
0             0      Afghanistan  AFG  32526562.0      594.323081
1             1          Albania  ALB   2889167.0     3945.217582
2             2          Algeria  ALG  39666519.0     4206.031232
3             3  American Samoa*  ASA     55538.0        0.000000
4             4          Andorra  AND     70473.0        0.000000
..          ...              ...  ...         ...             ...
196         196          Vietnam  VIE  91703800.0     2111.138024
197         197  Virgin Islands*  ISV    103574.0        0.000000
198         198            Yemen  YEM  26832215.0     1406.291651
199         199           Zambia  ZAM  16211767.0     1304.879014
200         200         Zimbabwe  ZIM  15602751.0      924.143819

[201 rows x 5 columns]

In [ ]:
df.isnull().sum()

Unnamed: 0        0
Country           0
Code              0
Population        0
GDP per Capita    0
dtype: int64

In [ ]:
df = df.fillna(method = 'pad')

/tmp/ipython-input-143778525.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method = 'pad')

In [ ]:
df

     Unnamed: 0          Country Code  Population  GDP per Capita
0             0      Afghanistan  AFG  32526562.0      594.323081
1             1          Albania  ALB   2889167.0     3945.217582
2             2          Algeria  ALG  39666519.0     4206.031232
3             3  American Samoa*  ASA     55538.0        0.000000
4             4          Andorra  AND     70473.0        0.000000
..          ...              ...  ...         ...             ...
196         196          Vietnam  VIE  91703800.0     2111.138024
197         197  Virgin Islands*  ISV    103574.0        0.000000
198         198            Yemen  YEM  26832215.0     1406.291651
199         199           Zambia  ZAM  16211767.0     1304.879014
200         200         Zimbabwe  ZIM  15602751.0      924.143819

[201 rows x 5 columns]

In [ ]:
df = df.fillna (method = 'bfill')

/tmp/ipython-input-1869733883.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna (method = 'bfill')

In [ ]:
df

     Unnamed: 0          Country Code  Population  GDP per Capita
0             0      Afghanistan  AFG  32526562.0      594.323081
1             1          Albania  ALB   2889167.0     3945.217582
2             2          Algeria  ALG  39666519.0     4206.031232
3             3  American Samoa*  ASA     55538.0        0.000000
4             4          Andorra  AND     70473.0        0.000000
..          ...              ...  ...         ...             ...
196         196          Vietnam  VIE  91703800.0     2111.138024
197         197  Virgin Islands*  ISV    103574.0        0.000000
198         198            Yemen  YEM  26832215.0     1406.291651
199         199           Zambia  ZAM  16211767.0     1304.879014
200         200         Zimbabwe  ZIM  15602751.0      924.143819

[201 rows x 5 columns]

In [ ]:
df = df.fillna (method = 'pad')

/tmp/ipython-input-831304187.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna (method = 'pad')

In [ ]:
df = df [25:50].dropna()

In [ ]:
df

    Unnamed: 0                   Country Code    Population  GDP per Capita
25          25                  Botswana  BOT  2.262485e+06     6360.138220
26          26                    Brazil  BRA  2.078475e+08     8538.589975
27          27    British Virgin Islands  IVB  3.011700e+04        0.000000
28          28                    Brunei  BRU  4.231880e+05    30554.729670
29          29                  Bulgaria  BUL  7.177991e+06     6993.477360
30          30              Burkina Faso  BUR  1.810557e+07      589.774414
31          31                   Burundi  BDI  1.117892e+07      277.068309
32          32                  Cambodia  CAM  1.557790e+07     1158.689904
33          33                  Cameroon  CMR  2.334418e+07     1217.260670
34          34                    Canada  CAN  3.585177e+07    43248.529910
35          35                Cape Verde  CPV  5.205020e+05     3080.178814
36          36           Cayman Islands*  CAY  5.996700e+04        0.000000
37          37  Central African Republic  CAF  4.900274e+06      323.201674
38          38                      Chad  CHA  1.403747e+07      775.695090
39          39                     Chile  CHI  1.794814e+07    13416.230040
40          40                     China  CHN  1.371220e+09     8027.683810
41          41                  Colombia  COL  4.822870e+07     6056.147717
42          42                   Comoros  COM  7.884740e+05      717.448850
43          43                     Congo  CGO  4.620330e+06     1851.199916
44          44            Congo, Dem Rep  COD  7.726681e+07      456.052741
45          45              Cook Islands  COK  0.000000e+00        0.000000
46          46                Costa Rica  CRC  4.807850e+06    11260.092160
47          47             Cote d'Ivoire  CIV  2.270156e+07     1398.989958
48          48                   Croatia  CRO  4.224404e+06    11535.829360
49          49                      Cuba  CUB  1.138956e+07        0.000000

In [ ]:
df = df.replace(to_replace=0, value=1234)

In [ ]:
df

    Unnamed: 0                   Country Code    Population  GDP per Capita
25          25                  Botswana  BOT  2.262485e+06     6360.138220
26          26                    Brazil  BRA  2.078475e+08     8538.589975
27          27    British Virgin Islands  IVB  3.011700e+04     1234.000000
28          28                    Brunei  BRU  4.231880e+05    30554.729670
29          29                  Bulgaria  BUL  7.177991e+06     6993.477360
30          30              Burkina Faso  BUR  1.810557e+07      589.774414
31          31                   Burundi  BDI  1.117892e+07      277.068309
32          32                  Cambodia  CAM  1.557790e+07     1158.689904
33          33                  Cameroon  CMR  2.334418e+07     1217.260670
34          34                    Canada  CAN  3.585177e+07    43248.529910
35          35                Cape Verde  CPV  5.205020e+05     3080.178814
36          36           Cayman Islands*  CAY  5.996700e+04     1234.000000
37          37  Central African Republic  CAF  4.900274e+06      323.201674
38          38                      Chad  CHA  1.403747e+07      775.695090
39          39                     Chile  CHI  1.794814e+07    13416.230040
40          40                     China  CHN  1.371220e+09     8027.683810
41          41                  Colombia  COL  4.822870e+07     6056.147717
42          42                   Comoros  COM  7.884740e+05      717.448850
43          43                     Congo  CGO  4.620330e+06     1851.199916
44          44            Congo, Dem Rep  COD  7.726681e+07      456.052741
45          45              Cook Islands  COK  1.234000e+03     1234.000000
46          46                Costa Rica  CRC  4.807850e+06    11260.092160
47          47             Cote d'Ivoire  CIV  2.270156e+07     1398.989958
48          48                   Croatia  CRO  4.224404e+06    11535.829360
49          49                      Cuba  CUB  1.138956e+07     1234.000000

First, let's create a DataFrame with some `NaN` values, similar to what we did before. This time, we'll use `interpolate()` to fill them.

In [ ]:
data = {'A': [1, 2, np.nan, 4, np.nan, 6],
        'B': [7, 8, np.nan, 10, 11, np.nan],
        'C': [13, np.nan, 15, 16, np.nan, 18]}

interpolate_df = pd.DataFrame(data)
print("Original DataFrame with NaN values:")
display(interpolate_df)

Original DataFrame with NaN values:

     A     B     C
0  1.0   7.0  13.0
1  2.0   8.0   NaN
2  NaN   NaN  15.0
3  4.0  10.0  16.0
4  NaN  11.0   NaN
5  6.0   NaN  18.0

Now, let's apply the `interpolate()` method. By default, it uses linear interpolation.

In [ ]:
interpolated_df = interpolate_df.interpolate()
print("DataFrame after linear interpolation:")
display(interpolated_df)

DataFrame after linear interpolation:

     A     B     C
0  1.0   7.0  13.0
1  2.0   8.0  14.0
2  3.0   9.0  15.0
3  4.0  10.0  16.0
4  5.0  11.0  17.0
5  6.0  11.0  18.0

Notice how the `NaN` values are now filled with values that are a linear estimation between the surrounding non-missing values. For example, in column 'A', the `NaN` between 2 and 4 is filled with 3. In column 'B', the first `NaN` (at index 2) is filled as 9 (between 8 and 10), and the last `NaN` (at index 5) remains `NaN` because there's no subsequent value to interpolate from, so you might use another method like `bfill()` or `ffill()` after interpolation if such cases occur.

In [ ]:
df.info

<bound method DataFrame.info of     Unnamed: 0                   Country Code    Population  GDP per Capita
25          25                  Botswana  BOT  2.262485e+06     6360.138220
26          26                    Brazil  BRA  2.078475e+08     8538.589975
27          27    British Virgin Islands  IVB  3.011700e+04     1234.000000
28          28                    Brunei  BRU  4.231880e+05    30554.729670
29          29                  Bulgaria  BUL  7.177991e+06     6993.477360
30          30              Burkina Faso  BUR  1.810557e+07      589.774414
31          31                   Burundi  BDI  1.117892e+07      277.068309
32          32                  Cambodia  CAM  1.557790e+07     1158.689904
33          33                  Cameroon  CMR  2.334418e+07     1217.260670
34          34                    Canada  CAN  3.585177e+07    43248.529910
35          35                Cape Verde  CPV  5.205020e+05     3080.178814
36          36           Cayman Islands*  CAY  5.996700e+04     1234.000000
37          37  Central African Republic  CAF  4.900274e+06      323.201674
38          38                      Chad  CHA  1.403747e+07      775.695090
39          39                     Chile  CHI  1.794814e+07    13416.230040
40          40                     China  CHN  1.371220e+09     8027.683810
41          41                  Colombia  COL  4.822870e+07     6056.147717
42          42                   Comoros  COM  7.884740e+05      717.448850
43          43                     Congo  CGO  4.620330e+06     1851.199916
44          44            Congo, Dem Rep  COD  7.726681e+07      456.052741
45          45              Cook Islands  COK  1.234000e+03     1234.000000
46          46                Costa Rica  CRC  4.807850e+06    11260.092160
47          47             Cote d'Ivoire  CIV  2.270156e+07     1398.989958
48          48                   Croatia  CRO  4.224404e+06    11535.829360
49          49                      Cuba  CUB  1.138956e+07     1234.000000>

In [ ]:
df1

     Unnamed: 0          Country Code  Population  GDP per Capita
0             0      Afghanistan  AFG  32526562.0      594.323081
1             1          Albania  ALB   2889167.0     3945.217582
2             2          Algeria  ALG  39666519.0     4206.031232
3             3  American Samoa*  ASA     55538.0        0.000000
4             4          Andorra  AND     70473.0        0.000000
..          ...              ...  ...         ...             ...
196         196          Vietnam  VIE  91703800.0     2111.138024
197         197  Virgin Islands*  ISV    103574.0        0.000000
198         198            Yemen  YEM  26832215.0     1406.291651
199         199           Zambia  ZAM  16211767.0     1304.879014
200         200         Zimbabwe  ZIM  15602751.0      924.143819

[201 rows x 5 columns]

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns